{% set name = 'bob.rppg.base' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  entry_points:
    - bob_rppg_cvpr14_extract_face_and_bg_signals.py = bob.rppg.cvpr14.script.extract_face_and_bg_signals:main
    - bob_rppg_cvpr14_video2skin.py = bob.rppg.cvpr14.script.video2skin:main
    - bob_rppg_cvpr14_illumination.py = bob.rppg.cvpr14.script.illumination_rectification:main
    - bob_rppg_cvpr14_motion.py = bob.rppg.cvpr14.script.motion_elimination:main
    - bob_rppg_cvpr14_filter.py = bob.rppg.cvpr14.script.filter:main
    - bob_rppg_chrom_pulse.py = bob.rppg.chrom.script.extract_pulse:main
    - bob_rppg_chrom_pulse_from_mask.py = bob.rppg.chrom.script.extract_pulse_from_mask:main
    - bob_rppg_ssr_pulse.py = bob.rppg.ssr.script.spatial_subspace_rotation:main
    - bob_rppg_ssr_pulse_from_mask.py = bob.rppg.ssr.script.ssr_from_mask:main
    - bob_rppg_base_get_heart_rate.py = bob.rppg.base.script.frequency_analysis:main
    - bob_rppg_base_compute_performance.py = bob.rppg.base.script.compute_performance:main
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob.extension
    - bob.core
    - bob.io.base
    - bob.io.image
    - bob.io.video
    - bob.ip.base
    - bob.ip.draw
    - bob.ip.color
    - bob.ip.facedetect
    - bob.ip.skincolorfilter
    - gridtk
  run:
    - python
    - setuptools
    - numpy
    - scipy
    - docopt
    - opencv
    - matplotlib
test:
  imports:
    - {{ name }}
  commands:
    - bob_rppg_cvpr14_extract_face_and_bg_signals.py --help
    - bob_rppg_cvpr14_video2skin.py --help
    - bob_rppg_cvpr14_illumination.py --help
    - bob_rppg_cvpr14_motion.py --help
    - bob_rppg_cvpr14_filter.py --help
    - bob_rppg_chrom_pulse.py --help
    - bob_rppg_chrom_pulse_from_mask.py --help
    - bob_rppg_ssr_pulse.py --help
    - bob_rppg_ssr_pulse_from_mask.py --help
    - bob_rppg_base_get_heart_rate.py --help
    - bob_rppg_base_compute_performance.py --help
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme

about:
  summary: Baseline Algorithms for Remote Photoplethysmography (rPPG)
  home: https://www.idiap.ch/software/bob/
  license: GPL-3.0
  license_family: GPL
